### ISSUE TITLE
config.example.toml has invalid example settings (commented out) 

### ISSUE THREAD

**Issue by atc0005** [atc0005/brick#42]
For example:

```toml
[ignoredusers]

# Fully-qualified path to a list of user accounts that should not be banned
# by this application. Lines beginning with a '#' character are ignored.
# Leading and trailing whitespace per line is ignored.
# ignored_users_file = "/home/ubuntu/users.brick-ignored.txt"
# file_path = "/tmp/users.brick-ignored.txt"
file_path = "/usr/local/etc/brick/users.brick-ignored.txt"
```

While it once was a valid config setting, the `ignored_users_file` is invalid for the current version of the application. Because we're attempting to offer multiple example paths, the fix is to replace the invalid settings name with the correct one: `file_path`. There is at least one more invalid setting like this one in the config file that I spotted, though there may be others.
